### PR TITLE
Fix the concurrent editing issue of Move Operation

### LINKED ISSUE #195: Fix the concurrent editing issue of Move Operation
**Description**:

We fixed a bug related to Move Operation in https://github.com/yorkie-team/yorkie-js-sdk/pull/196 in JS SDK.
This bug fix should also be applied in Yorkie.

**Why**:

Applying this patch will not cause any issues with snapshots Agent.

### PR DESCRIPTION
**Pull request by hackerwins**
**What this PR does / why we need it**:

Fix the concurrent editing issue of Move Operation

**Which issue(s) this PR fixes**:

Fixes #195

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

File: pkg/document/json/rga_tree_list.go [hunk 1]
```diff
@@ -63,6 +63,20 @@ func (n *RGATreeListNode) Element() Element {
...
+	return n.elem.CreatedAt()
+}
+
+// PositionedAt returns the time this element was positioned.
+func (n *RGATreeListNode) PositionedAt() *time.Ticket {
+	if n.elem.MovedAt() != nil {
+		return n.elem.MovedAt()
+	}
+
+	return n.elem.CreatedAt()
```
Comment (dc7303) [inline pkg/document/json/rga_tree_list.go:77]:
```suggestion
	return n.CreatedAt()
```

**Review by dc7303 — APPROVED** [review]
LGTM 👍

**Review by ppeeou — APPROVED** [review]
LGTM
