### PR TITLE
fix: resolve flaky TestBatchExpiration/Process_Expire_Batch test

### LINKED ISSUE #1412: TestBatchExpiration/Process_Expire_Batch fails intermittently
**What would you like to be added**:

We are experiencing intermittent failures in the TestBatchExpiration/Process_Expire_Batch test. This introduces noise during CI runs, especially when working on unrelated features.

```go
=== RUN   TestBatchExpiration/Process_Expire_Batch
    limiter_test.go:381: 
        	Error:      	Not equal: 
        	            	expected: 40
        	            	actual  : 32
    ...
        	Error:      	Not equal: 
        	            	expected: 60
        	            	actual  : 52
```

This test seems to depend on timing or batch expiration behavior that may vary based on runtime conditions. We suspect some nondeterminism in how batches are processed or expired.

Impact
- Inconsistent test results in CI.
- Distracts from actual regressions.
- Developers often rerun CI jobs without real fixes, reducing confidence in the suite.

We may need to refactor this test to reduce reliance on timing or side effects.
**Why is this needed**:

### PR DESCRIPTION
**Pull request by minwoo1999**
**What this PR does / why we need it**:

This PR fixes intermittent failures in the `TestBatchExpiration/Process_Expire_Batch` test that were causing CI noise and reducing developer confidence. The test was relying on fixed timing assumptions (`time.Sleep`) which made it flaky in different CI environments.

The solution replaces time-based waiting with channel-based synchronization to track actual callback completion, eliminating timing dependencies and race conditions.

**Which issue(s) this PR fixes**:
close #1412 

Fixes # (CI flaky test issue)

**Special notes for your reviewer**:
- Added a `createCallbackWithTracking` helper that uses channels to signal callback completion
- The test now waits for actual callback execution rather than assuming timing
- Verified with 15 consecutive test runs to ensure stability

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

**Additional documentation**:

```docs
NONE
```

**Checklist**:

- [x] Added relevant tests or not required (improved existing test reliability)
- [x] Addressed and resolved all CodeRabbit review comments
- [x] Didn't break anything (verified with multiple test runs and full package tests)

## Summary by CodeRabbit

* **Tests**
  * Improved reliability and robustness of batch expiration tests by explicitly tracking callback completions, reducing reliance on sleep and enhancing test determinism.

### CODE REVIEW

**Comment by hackerwins** [comment]
@window9u Could you review this PR?

**Comment by window9u** [comment]
@hackerwins Sure! I'll try to review it until this week!

File: pkg/limit/limiter_test.go [hunk 1]
```diff
@@ -376,11 +390,35 @@ func TestBatchExpiration(t *testing.T) {
...
 		time.Sleep(expireInterval / 2)
+
+		// Wait for each batch with both count checking and completion tracking
 		for i := range batchNum {
-			assert.Equal(t, totalKeys+expireBatchSize*i, o.len())
-			time.Sleep(expireInterval)
+			expectedCount := totalKeys + expireBatchSize*(i+1)
+
+			// First, wait for the callbacks to actually execute
+			for j := 0; j < expireBatchSize; j++ {
```
Comment (blurfx) [inline pkg/limit/limiter_test.go]: I think it would be good to use 'range' here as well.
```suggestion
			for j := range expireBatchSize {
```

File: pkg/limit/limiter_test.go [hunk 2]
```diff
@@ -376,11 +390,35 @@ func TestBatchExpiration(t *testing.T) {
...
+		// Wait for immediate callbacks to be processed
+		for i := 0; i < totalKeys; i++ {
+			select {
+			case <-completionChan:
+			case <-time.After(100 * time.Millisecond):
+				t.Fatalf("Timeout waiting for immediate callback %d", i)
+			}
+		}
+
 		time.Sleep(expireInterval / 2)
```
Comment (window9u) [inline pkg/limit/limiter_test.go]: How about remove this line too?

Comment (minwoo1999) [reply pkg/limit/limiter_test.go]: Thanks for the suggestion!

I'll try removing it and see if the test remains stable. Appreciate the input! 🙏

**Review by hackerwins — APPROVED** [review]
Thanks for your contribution.
