### PR TITLE
Remove panic in types.EncodeOperation

### LINKED ISSUE #50: Remove panic from server code
Currently, panic is called when an exception such as an error occurs in the server code. The server goes down, but it is easier to grasp the error situation.

However, in the production environment, it should be changed to return an error instead of panic so that the server does not stop.

### PR DESCRIPTION
**Pull request by gmlwo530**
Remove panic in types.EncodeOperation. And change return value of types.EncodeOperation to ([][]bytes, error).
Add errors.New() with message used in panic.

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind deprecation
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #50 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

### CODE REVIEW

File: yorkie/backend/mongo/client.go [hunk 1]
```diff
@@ -311,6 +311,12 @@ func (c *Client) CreateChangeInfos(
 		var modelChanges []mongo.WriteModel
 
 		for _, c := range changes {
+			encodedOperations, err := types.EncodeOperation(c.Operations())
+			if err != nil {
+				log.Logger.Error(err)
```
Comment (hackerwins) [inline yorkie/backend/mongo/client.go:316]: Since log.Logger.Error prints stack trace, it would be better to call only when an error occurs in the method, not our code. Can we move it to below position?
https://github.com/yorkie-team/yorkie/pull/84/files#diff-5a46bd121e6927f28ccfccbafe3ea9ffL46

**Review by hackerwins — COMMENTED** [review]
Thanks for your contribution.

File: yorkie/types/change_info.go [hunk 2]
```diff
@@ -37,18 +39,18 @@ type ChangeInfo struct {
 	Operations [][]byte           `bson:"operations"`
 }
 
-func EncodeOperation(operations []operation.Operation) [][]byte {
+func EncodeOperation(operations []operation.Operation) ([][]byte, error) {
```
[the remark this answers is not in the document]
Comment (gmlwo530) [reply yorkie/types/change_info.go:42]: OK, I will change it

File: yorkie/backend/mongo/client.go (hunk 1 above)
Comment (gmlwo530) [reply yorkie/backend/mongo/client.go]: I changed position of `log.Logger.Error(err)`. Is it right?

**Comment by hackerwins** [comment]
@gmlwo530 Thanks for your contribution.
