### PR TITLE
Prevent project secret key from granting full user access

### LINKED ISSUE #813: Project Secret Key grants the same permissions as the owner of the project.
**What happened**:

The Project Secret Key grants the same permissions as the owner of the project. For example, when Admin A owns Project B and uses the Secret Key of that project, they can access other projects owned by Admin A as well. This occurs because accessing a project via the Project Secret Key returns the user who owns the project.

image

**What you expected to happen**:

The Project Secret Key should only provide access to the specific project it belongs to and not grant access to other projects owned by the same user.

**How to reproduce it (as minimally and precisely as possible)**:

The issue can be reproduced by using the Project Secret Key to access a project and observing that it inadvertently provides access to other projects owned by the same user.

**Anything else we need to know?**:

It is suggested that a solution could involve adding a flag to the User to distinguish between Admin and Project access rights.

```go
claims, err := i.tokenManager.Verify(authorization)
if err == nil {
    user, err := users.GetUserByName(ctx, i.backend, claims.Username)
    if err == nil {
        return user, nil
    }
}

project, err := projects.GetProjectFromSecretKey(ctx, i.backend, authorization)
if err == nil {
    user, err := users.GetUserByID(ctx, i.backend, project.Owner)
    if err == nil {
        return user, nil // Need to return Project permissions, not Admin permissions
    }
}
``` 

**Environment**:
- Operating system: ALL
- Browser and version: ALL
- Yorkie version (use `yorkie version`): v0.4.14
- Yorkie JS SDK version: NONE

### PR DESCRIPTION
**Pull request by SANGHEEJEONG**
**What this PR does / why we need it**:

<h3>Issue</h3>
<ul>
<li><strong>Problem</strong>: When Admin A (owner of Project B) uses the secret key of Project B, they are unintentionally granted access to other projects they own.</li>
<li><strong>Cause</strong>: The current logic returns the project owner as a user, which implicitly grants full access across all projects owned by that user.</li>
</ul>
<pre><code class="language-go">project, err := projects.GetProjectFromSecretKey(ctx, i.backend, authorization)
if err == nil {
    user, err := users.GetUserByID(ctx, i.backend, project.Owner)
    if err == nil {
        return user, nil // This returns full user-level access instead of project-scoped access
    }
}

</code></pre>

<br>

<h3>Ideal Behavior</h3>

Item | Current (As-Is) | Desired (To-Be)
-- | -- | --
Project X's secret key | Grants access to all of Developer A’s projects | Grants access to Project X only
Developer A’s user token | Grants access to all of their own projects | Unchanged — full access to all own projects
---
**Which issue(s) this PR fixes**:
Fixes #813 

---

### Summary of Changes

To resolve this, I introduce the concept of access scope in the `User` model.

- **User Token** → Returns `User` with `AccessScopeAdmin`
- **Project Key** → Returns `User` with `AccessScopeProject` and sets the `Project` in context

This allows downstream handlers to determine the access level and use it appropriately.
```go
// If access scope is project, verify the project from context
if user.AccessScope == types.AccessScopeProject {
	ctxProject := projects.From(ctx)
	if ctxProject.Name != projectName {
		return nil, fmt.Errorf("project mismatch: key is for %s, got %s", ctxProject.Name, projectName)
	}
	return ctxProject, nil
}

// For admin scope, fetch the project
project, err := projects.GetProject(ctx, s.backend, user.ID, projectName)
if err != nil {
	return nil, err
}
```
---
<br>

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE

```

**Additional documentation**:

```docs

```

**Checklist**:

- [ ] Added relevant tests or not required
- [ ] Addressed and resolved all CodeRabbit review comments
- [ ] Didn't break anything

## Summary by CodeRabbit

* **New Features**
  * User accounts now include an access scope, distinguishing between full administrative access and project-specific access.

* **Refactor**
  * Improved authorization logic for project access, ensuring consistent enforcement of user access scopes.
  * Authentication process now enriches request context with user and project information for streamlined access control.

* **Tests**
  * Added integration test to verify that document access is restricted across different projects.
  * Introduced helper functions to simplify project creation and unauthorized access testing in tests.

### CODE REVIEW

File: server/rpc/admin_server.go [hunk 1]
```diff
@@ -839,3 +823,29 @@ func (s *adminServer) RotateProjectKeys(
...
+
+	// If access scope is project, verify the project from context
+	if user.AccessScope == types.AccessScopeProject {
+		ctxProject := projects.From(ctx)
+		if ctxProject.Name != projectName {
+			return nil, fmt.Errorf("project mismatch: key is for %s, got %s", ctxProject.Name, projectName)
+		}
+
+		return ctxProject, nil
+	}
```
Comment (blurfx) [inline server/rpc/admin_server.go]: I suggest explicitly checking for every `AccessScope` and returning an error if it is not a valid `AccessScope` to prevent granting incorrect permissions from several edge cases, like when new `AccessScope` types are added in the future. If you think it's okay with this change, it would be better to use a `switch` statement instead of `if`.

File: server/rpc/admin_server.go [hunk 2]
```diff
@@ -839,3 +823,29 @@ func (s *adminServer) RotateProjectKeys(
 		Project: converter.ToProject(newProject),
 	}), nil
 }
+
+// GetProjectWithAuth fetches the project based on the user's access scope.
+func (s *adminServer) GetProjectWithAuth(
```
Comment (kokodak) [inline server/rpc/admin_server.go:828]: Authorization is a critical aspect, so I believe it's essential to have test coverage to verify that #813 has been truly resolved. Specifically, we should add tests for the `GetProjectWithAuth`.

The tests should cover the following cases:
1. When a request is made using a Project Secret Key, ensure that it cannot access any project other than the one it belongs to.
2. When a request is made using a User Token, ensure that it continues to behave as it did before.

File: server/rpc/admin_server.go [hunk 3]
```diff
@@ -839,3 +823,29 @@ func (s *adminServer) RotateProjectKeys(
...
+	ctx context.Context,
+	projectName string,
+) (*types.Project, error) {
+	user := users.From(ctx)
+
+	// If access scope is project, verify the project from context
+	if user.AccessScope == types.AccessScopeProject {
+		ctxProject := projects.From(ctx)
+		if ctxProject.Name != projectName {
+			return nil, fmt.Errorf("project mismatch: key is for %s, got %s", ctxProject.Name, projectName)
```
Comment (kokodak) [inline server/rpc/admin_server.go]: I think it would be good to return `ErrUnauthenticated` error.
Something like this:
```suggestion
			return nil, fmt.Errorf("project mismatch: key is for %s, got %s: %w", ctxProject.Name, projectName, ErrUnauthenticated)
```

This will allow for verification in this way:
```go
assert.Equal(t, connect.CodeUnauthenticated, connect.CodeOf(err))
```

File: server/rpc/admin_server.go (hunk 1 above)
Comment (SANGHEEJEONG) [reply server/rpc/admin_server.go]: Thank you for letting me know!

File: server/rpc/admin_server.go (hunk 2 above)
Comment (SANGHEEJEONG) [reply server/rpc/admin_server.go:828]: I've confirmed that the second case is already covered by existing tests, so I added a test only for the first case. 
Thanks!

**Review by hackerwins — APPROVED** [review]
Thanks for your contribution.
