### PR TITLE
Remove panics from the converter

### LINKED ISSUE #50: Remove panic from server code
Currently, panic is called when an exception such as an error occurs in the server code. The server goes down, but it is easier to grasp the error situation.

However, in the production environment, it should be changed to return an error instead of panic so that the server does not stop.

### PR DESCRIPTION
**Pull request by hackerwins**
**What this PR does / why we need it**:

Remove panics from the converter.

If an error occurs in the converter, the converter must return an error
and allow the caller to decide how to handle it.

In particular, when a request that is not supported by the old server is
given, the server should return an error response instead of being
terminated.

This commit is based on the recommendations below.
https://github.com/uber-go/guide/blob/master/style.md#dont-panic

**Which issue(s) this PR fixes**:

Fixes #50

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [ ] Didn't break anything

### CODE REVIEW

File: pkg/document/proxy/text_proxy.go [hunk 1]
```diff
@@ -70,3 +70,30 @@ func (p *TextProxy) Edit(from, to int, content string) *TextProxy {
 	}
 	return p
 }
+
+// Select stores that the given range has been selected.
+func (p *TextProxy) Select(from, to int) *TextProxy {
```
Comment (dc7303) [inline pkg/document/proxy/text_proxy.go:75]: It seems to be outside the scope of the current PR title and content. I think we can revise the title and content so we can see that this feature has been added to this PR.
Let me know what you think.

**Review by dc7303 — APPROVED** [review]
LGTM :) That's great work!
I gave you an opinion. please check.

File: pkg/document/proxy/text_proxy.go (hunk 1 above)
Comment (hackerwins) [reply pkg/document/proxy/text_proxy.go:75]: Thank you for the review. I have added the missing features to increase coverage. I'll add it to the body of this commit.
