### PR TITLE
Fix the value type of Counter and remove double type from Counter

### LINKED ISSUE #436: Fix the value type of Counter and remove double type from Counter
**Description**:

Fix the value type of `Counter` and remove `Double` type.

A. Specify the type explicitly when creating a Counter object.

```js
doc.update((root) => {
  // AS-IS
  root.counter = new yorkie.Counter(1);

  // TO-BE
  root.counter = new yorkie.Counter(yorkie.LongType, 1);
});
```

B. Remove the Double type support.

Only supports `IntType` and `LongType`.

```js
doc.update((root) => {
  root.intCounter = new yorkie.Counter(yorkie.IntType, 1); // int32
  root.longCounter = new yorkie.Counter(yorkie.LongType, 1); // int64
});
```

C. Cast the argument passed to `increase` to the specified type of the Counter.

```js
doc.update((root) => {
  root.counter = new yorkie.Counter(yorkie.IntType, 1);
  root.counter.increase(3.5); // Cast 3.5 to integer.
});
```

D. Allow for [integer overflow](https://en.wikipedia.org/wiki/Integer_overflow).

```go
number := int32(math.MaxInt32)
number += 1
fmt.Println(number) // -2147483648
```

**Why**:

If the type of Counter is changed dynamically, users may be confused.

### PR DESCRIPTION
**Pull request by cozitive**
**What this PR does / why we need it**:
To prevent dynamic type change of Counter, explicit type specification is required in Counter constructor. Moreover, double type is removed in Counter to mitigate confusion.

**Which issue(s) this PR fixes**:

Fixes #436

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Users should specify the type of Counter when calling the constructor.
```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

### CODE REVIEW

File: pkg/document/crdt/counter.go [hunk 1]
```diff
@@ -59,32 +55,77 @@ type Counter struct {
 }
 
 // NewCounter creates a new instance of Counter.
-func NewCounter(value interface{}, createdAt *time.Ticket) *Counter {
-	switch val := value.(type) {
-	case int:
-		if math.MaxInt32 < val || math.MinInt32 > val {
+func NewCounter(valueType CounterType, value interface{}, createdAt *time.Ticket) *Counter {
+	switch valueType {
+	case IntegerCnt:
```
Comment (hackerwins) [inline pkg/document/crdt/counter.go:60]: Both `NewCounter` and `Increase` have the same logic that casts the given type to a predefined type. How about defining the below functions and removing duplicated logic from `NewCounter` and `Increase`?

`func castInt(value interface{}): int32`
`func castLong(value interface{}): int64`

**Review by hackerwins — COMMENTED** [review]
Thanks for your contribution.
I left a brief comment.

**Review by hackerwins — APPROVED** [review]
Thanks for your contribution.
