### PR TITLE
Fix FindDocInfosByKeys when keys is empty

### LINKED ISSUE #943: Error occurs when executing `FindDocInfosByKeys` query with empty docKeys argument
**What happened**:
When performing the `FindDocInfosByKeys` query with an empty array for docKeys, the server encounters a critical issue. Specifically, the server crashes with the following error:
```
2024-07-26T01:27:13.710+0900    WARN    a16     RPC : "/yorkie.v1.AdminService/GetDocuments" 
1.773583ms: &{"project_name:\"default\"" {'\x00' "/yorkie.v1.AdminService/GetDocuments" 
%!q(bool=false) '\x00'} {"[::1]:49484" "connect" map[]} map["Authorization":
["cqh6cnh97i624rnkavk0"] "Content-Length":["70"] "Content-Type":["application/json"] "Host":
["localhost:8080"]] "POST"} => "find documents: (BadValue) $in needs an array"
```

**How to reproduce it (as minimally and precisely as possible)**:
1. Execute the `FindDocInfosByKeys` query with an empty array for docKeys.
2. Observe the server crashing and generating the mentioned error.

**Anything else we need to know?**:

**Environment**:
- Operating system:
- Browser and version:
- Yorkie version (use `yorkie version`): v0.4.28
- Yorkie JS SDK version:

### PR DESCRIPTION
**Pull request by blurfx**
**What this PR does / why we need it**:

Fix the mongodb query keys slice to return an empty slice if it is empty.

Currently, FindDocInfosByKeys throws a query error when passing an empty slice of keys.

**Which issue(s) this PR fixes**:

Fixes #943 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

**Additional documentation**:

```docs

```

**Checklist**:
- [x] Added relevant tests or not required
- [x] Didn't break anything

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved robustness of the document retrieval process by preventing unnecessary database queries when no document keys are provided, resulting in a more efficient and responsive application.
- **Tests**
	- Added a new test case to ensure the function correctly handles scenarios where an empty slice of keys is provided, enhancing the reliability of the document retrieval functionality.

### CODE REVIEW

File: server/backend/database/mongo/client.go [hunk 1]
```diff
@@ -769,6 +769,9 @@ func (c *Client) FindDocInfosByKeys(
 	projectID types.ID,
 	docKeys []key.Key,
 ) ([]*database.DocInfo, error) {
+	if len(docKeys) == 0 {
+		return []*database.DocInfo{}, nil
```
Comment (hackerwins) [inline server/backend/database/mongo/client.go:773]: https://github.com/uber-go/guide/blob/master/style.md#nil-is-a-valid-slice

```suggestion
		return nil, nil
```

**Review by hackerwins — APPROVED** [review]
Thanks for your contribution.
